import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Kidso - Modern Kindergarten &amp; Baby Care',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
      <head>
      <meta charSet="utf-8" />
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico" />
      <link rel="stylesheet" href="css/bootstrap.min.css" />
      <link rel="stylesheet" href="css/animate.min.css" />
      <link rel="stylesheet" href="css/magnific-popup.css" />
      <link rel="stylesheet" href="fontawesome/css/all.min.css" />
      <link rel="stylesheet" href="font-flaticon/flaticon.css" />
      <link rel="stylesheet" href="css/dripicons.css" />
      <link rel="stylesheet" href="css/slick.css" />
      <link rel="stylesheet" href="css/meanmenu.css" />
      <link rel="stylesheet" href="css/default.css" />
      <link rel="stylesheet" href="css/style.css" />
      <link rel="stylesheet" href="css/responsive.css" />
      </head> 

      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
