import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Script from "next/script"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Kidso - Modern Kindergarten & Baby Care',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
      <head>
      <meta charSet="utf-8" />
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico" />
      <link rel="stylesheet" href="css/bootstrap.min.css" />
      <link rel="stylesheet" href="css/animate.min.css" />
      <link rel="stylesheet" href="css/magnific-popup.css" />
      <link rel="stylesheet" href="fontawesome/css/all.min.css" />
      <link rel="stylesheet" href="font-flaticon/flaticon.css" />
      <link rel="stylesheet" href="css/dripicons.css" />
      <link rel="stylesheet" href="css/slick.css" />
      <link rel="stylesheet" href="css/meanmenu.css" />
      <link rel="stylesheet" href="css/default.css" />
      <link rel="stylesheet" href="css/style.css" />
      <link rel="stylesheet" href="css/responsive.css" />
      </head> 

      <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>


    <Script type="text/javascript" id="hs-script-loader" async defer src="js/vendor/modernizr-3.5.0.min.js"/> 
    <Script type="text/javascript" id="hs-script-loader" async defer src="js/vendor/jquery-3.6.0.min.js"/>
    <Script type="text/javascript" id="hs-script-loader" async defer src="js/popper.min.js"/>
    <Script type="text/javascript" id="hs-script-loader" async defer src="js/bootstrap.min.js"/>
    <Script type="text/javascript" id="hs-script-loader" async defer src="js/slick.min.js"/>
    <Script type="text/javascript" id="hs-script-loader" async defer src="js/paroller.js"/>
    <Script type="text/javascript" id="hs-script-loader" async defer src="js/wow.min.js"/>
    <Script type="text/javascript" id="hs-script-loader" async defer src="js/parallax.min.js"/>
    <Script type="text/javascript" id="hs-script-loader" async defer src="js/jquery.waypoints.min.js"/>
    <Script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js"/>
    <Script type="text/javascript" id="hs-script-loader" async defer src="js/jquery.scrollUp.min.js"/>
    <Script type="text/javascript" id="hs-script-loader" async defer src="js/jquery.meanmenu.min.js"/> 
    <Script type="text/javascript" id="hs-script-loader" async defer src="js/jquery.magnific-popup.min.js"/> 
    <Script type="text/javascript" id="hs-script-loader" async defer src="js/parallax-scroll.js"/> 
    <Script type="text/javascript" id="hs-script-loader" async defer src="js/element-in-view.js"/> 
    <Script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"/>
    <Script src="https://unpkg.com/imagesloaded@5/imagesloaded.pkgd.js"/>
    <Script type="text/javascript" id="hs-script-loader" async defer src="js/main.js"/>  
    
    </body>
    </html>
  )
}
